# x86_64-w64-mingw32.cmake for project URANIA

set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_SYSTEM_NAME Windows)

set(CROSS_PREFIX x86_64-w64-mingw32-)
set(CROSS_TOOLCHAIN_PATH /usr/x86_64-w64-mingw32)

set(CMAKE_C_COMPILER /usr/bin/${CROSS_PREFIX}clang)
set(CMAKE_CXX_COMPILER /usr/bin/${CROSS_PREFIX}clang++)

#set(CMAKE_FIND_ROOT_PATH ${CROSS_TOOLCHAIN_PATH}/)
#set(CMAKE_INCLUDE_PATH ${CROSS_TOOLCHAIN_PATH}/include)
#set(CMAKE_LIBRARY_PATH ${CROSS_TOOLCHAIN_PATH}/lib)

set(CMAKE_INSTALL_PREFIX /usr/local/mw)


#eof
